# .github/workflows/CD-Prod.yml
name: Terraform CD - Prod

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan-prod:
    name: Plan for Prod
    uses: ./.github/workflows/tf-plan.yml
    with:
      subdirectory: "terraform/Personal-Prod"
      environment_name: prod-plan
      plan_filename: prod.tfplan
      artifact_name: terraform-prod-plan
      tfstate_key: "dirbased-personal-prod.tfstate"
      checkout_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      is_pr: ${{ github.event_name == 'pull_request' }}

  apply-prod:
    name: Apply to Prod
    needs: [plan-prod]
    uses: ./.github/workflows/tf-apply.yml
    # Only apply on push (i.e., after the PR merges)
    if: >
      github.event_name == 'push' &&
      needs.plan-prod.outputs.tfplan_exitcode == '2'
    with:
      subdirectory: "terraform/Personal-Prod"
      environment_name: prod-apply
      plan_filename: prod.tfplan
      artifact_name: terraform-prod-plan
      tfstate_key: "dirbased-personal-prod.tfstate"
      checkout_ref: ${{ github.sha }}
