# .github/workflows/CI.yml
name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install Checkov
        run: |
          pip install --upgrade pip
          pip install checkov

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Validate (all subdirectories)
        run: |
          for dir in $(find terraform -type d -not -path "*/.*"); do
            if [ -f "$dir/main.tf" ] || [ -f "$dir/*.tf" ]; then
              echo "Validating $dir..."
              terraform -chdir="$dir" init -backend=false
              terraform -chdir="$dir" validate
            fi
          done

      - name: Lint with TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: Run Checkov
        run: checkov -d .